application: lively-shelter-687
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: login.php

- url: /index
  script: index.php
  
- url: /imageProxy
  script: imageProxy.php
  
- url: /pruebaMail
  script: pruebaMail.php

- url: /uploadImage
  script: uploadImage.php
  
- url: /pruebaCifrado
  script: pruebaCifrado.php  
  
- url: /bienvenida
  script: bienvenida.php
  
- url: /userInactivo
  script: userInactivo.php  

- url: /agregarAdminAdmin
  script: agregarAdminAdmin.php
  
- url: /agregarAdminPsico
  script: agregarAdminPsico.php
  
- url: /actualizarAnotacion
  script: actualizarAnotacion.php

- url: /agregarPaciente
  script: agregarPaciente.php
  
- url: /activarPsicologo
  script: activarPsicologo.php 

- url: /activarAdmin
  script: activarAdmin.php   

- url: /config
  script: config.php

- url: /logOut
  script: logOut.php   
  
- url: /config_mongo
  script: config_mongo.php
  
- url: /contarregistros
  script: contarregistros.php

- url: /actualizarAdminPsico
  script: actualizarAdminPsico.php
  
- url: /examplecharts
  script: examplecharts.php

- url: /helloworld
  script: helloworld.php
  
- url: /AdminAdmin
  script: indexAdminAdmin.php
  
- url: /AdminPsico
  script: indexAdminPsico.php
  
- url: /edicionPsico
  script: edicionPsico.php
  
- url: /indexPaciente
  script: indexPaciente.php

- url: /list-paci
  script: list-paci.php
  
- url: /list-admin
  script: list-admin.php

- url: /historiaClinica
  script: historiaClinica.php
  
- url: /AgregarHistoria
  script: AgregarHistoria.php

- url: /descarga
  script: /tcpdf/examples/example_002.php

- url: /utilidades
  script: utilidades.php
  
- url: /list-user
  script: list-user.php
  
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /jquery
  static_dir: jquery
  
- url: /fonts
  static_dir: fonts
  
